framework:
    cache:
        pools:
            nutripetit.off_api:
                adapter: cache.adapter.redis
                provider: '%env(REDIS_URL)%'
                default_lifetime: 604800

            nutripetit.scores:
                adapter: cache.adapter.redis
                provider: '%env(REDIS_URL)%'
                default_lifetime: 2592000

when@test:
    framework:
        cache:
            app: cache.adapter.array

when@prod:
    framework:
        cache:
            pools:
                nutripetit.off_api:
                    adapter: cache.adapter.redis
                    provider: '%env(REDIS_URL)%'
                    default_lifetime: 604800

                nutripetit.scores:
                    adapter: cache.adapter.redis
                    provider: '%env(REDIS_URL)%'
                    default_lifetime: 2592000
