services:

  ###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    container_name: nutripetit-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-nutripetit}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-nutripetit}
      POSTGRES_USER: ${POSTGRES_USER:-nutripetit}
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-nutripetit}", "-U", "${POSTGRES_USER:-nutripetit}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
  ###< doctrine/doctrine-bundle ###

  ###> redis ###
  redis:
    image: redis:7-alpine
    container_name: nutripetit-redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 5s
      retries: 5
  ###< redis ###

  ###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    container_name: nutripetit-mailpit
    restart: unless-stopped
    ports:
      - "1026:1025"
      - "8026:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
  ###< symfony/mailer ###

volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
  ###< doctrine/doctrine-bundle ###

  ###> redis ###
  redis_data:
  ###< redis ###
