<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260609092518 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE products (ean VARCHAR(13) NOT NULL, name VARCHAR(255) NOT NULL, brand VARCHAR(255) DEFAULT NULL, image_url VARCHAR(500) DEFAULT NULL, ingredients_raw TEXT DEFAULT NULL, nutriments JSON DEFAULT \'{}\' NOT NULL, allergens JSON DEFAULT \'[]\' NOT NULL, additives JSON DEFAULT \'[]\' NOT NULL, off_raw_data JSON DEFAULT \'{}\' NOT NULL, fetched_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (ean))');
        $this->addSql('CREATE TABLE scan_sessions (id UUID NOT NULL, baby_age_months INT DEFAULT NULL, user_agent VARCHAR(500) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_active_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_session_last_active ON scan_sessions (last_active_at)');
        $this->addSql('CREATE TABLE score_results (id UUID NOT NULL, final_score INT NOT NULL, level VARCHAR(20) NOT NULL, applied_rules JSON DEFAULT \'[]\' NOT NULL, algo_version VARCHAR(20) NOT NULL, baby_age_months INT DEFAULT NULL, calculated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, product_ean VARCHAR(13) NOT NULL, scan_session_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FE2BC1804BBB0846 ON score_results (scan_session_id)');
        $this->addSql('CREATE INDEX idx_score_product ON score_results (product_ean)');
        $this->addSql('CREATE INDEX idx_score_calculated_at ON score_results (calculated_at)');
        $this->addSql('CREATE TABLE scoring_rules (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(50) NOT NULL, label VARCHAR(100) NOT NULL, description TEXT NOT NULL, algo_version VARCHAR(20) NOT NULL, points_impact INT NOT NULL, threshold_value DOUBLE PRECISION DEFAULT NULL, threshold_unit VARCHAR(20) DEFAULT NULL, age_min_months INT DEFAULT NULL, age_max_months INT DEFAULT NULL, source_name VARCHAR(255) NOT NULL, source_url VARCHAR(500) NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_rule_code_version ON scoring_rules (code, algo_version)');
        $this->addSql('CREATE INDEX idx_rule_active ON scoring_rules (is_active)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE score_results ADD CONSTRAINT FK_FE2BC180879E927F FOREIGN KEY (product_ean) REFERENCES products (ean) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE score_results ADD CONSTRAINT FK_FE2BC1804BBB0846 FOREIGN KEY (scan_session_id) REFERENCES scan_sessions (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE score_results DROP CONSTRAINT FK_FE2BC180879E927F');
        $this->addSql('ALTER TABLE score_results DROP CONSTRAINT FK_FE2BC1804BBB0846');
        $this->addSql('DROP TABLE products');
        $this->addSql('DROP TABLE scan_sessions');
        $this->addSql('DROP TABLE score_results');
        $this->addSql('DROP TABLE scoring_rules');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
