parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Auto-tag de tous les RuleEvaluator
    # Permet au ScoreCalculator de les récupérer via #[AutowireIterator]
    _instanceof:
        App\Service\Scoring\RuleEvaluator:
            tags: ['app.rule_evaluator']
